import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Layout from '../components/layout';
import { page } from '../styles/GlobalStyled';
import styled from 'styled-components';

const StyledAbout = styled(page)`
    text-align: center;

    .about-wrapper {
        display: flex;
        flex-direction: column;
        min-height: calc(90vh -1rem);
        width: 100vw;
        max-width: var(--max-width);
        margin: 1rem auto;

        article {
            min-width: 280px;
            width: 100vw;
            max-width: 500px;
            background: white;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            margin-top: 0.5rem;
            /* justify-content: space-between; */
            #about-image1,
            #about-image2 {
                max-height: 500px;
                margin: 0;
                text-align: left;
                img {
                    object-fit: cover;
                    width: 100vw;
                    min-width: 280px;
                }
                /* background: grey; */
            }
            .about-content {
                display: flex;
                flex-direction: column;
                justify-content: flex-start;
                width: 100vw;
                min-height: 400px;
                min-width: 280px;
                height: auto;
                margin: 0;
                background: var(--primary-opaque);
                padding: 5px;
                h2 {
                    text-align: center;
                    font-size: 2rem;
                }
                p {
                    /* line-height: 1.4rem; */
                    text-align: left;
                    margin: 1rem 0;
                    min-width: 280px;
                }
            }
        }
    }
    @media only screen and (min-width: 500px) {
        /* padding-bottom: 150px; */
        article {
            .p-wrapper {
                display: flex;
                flex-direction: column;
                justify-content: space-around;
                height: 350px;
            }
            /* flex-direction: row; */
            position: relative;
            min-height: 100vh;
            width: 90vw !important;
            max-width: 1200px !important;
            margin: 5px auto !important;
            align-items: center;
            .about-content {
                position: absolute;
                bottom: 3.5rem;
                /* right: 0; */
                width: 90vw !important;
                max-width: 800px;
                min-height: 450px !important;
                padding: 0 !important;
                h2 {
                    margin-top: 15px;
                    margin-bottom: 20px;
                }
                p {
                    margin: 4px 0 4px 0 !important;

                    line-height: 1.2rem;
                    padding: 0 15px !important;
                }
            }
            #about-image1,
            #about-image2 {
                max-width: 800px;
                img {
                    width: 90vw !important;
                    height: 50vh;
                    max-width: 800px;
                }
            }
        }
        #footer {
            margin-top: 50px;
        }
    }
`;

export default function about() {
    return (
        <Layout>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet" />
            </Head>
            <StyledAbout>
                <h1>flamingoについて</h1>
                <div className="about-wrapper">
                    <article>
                        <div id="about-image1">
                            <img src="/salon1.jpg" alt="Salon room" loading="lazy" />
                        </div>
                        <div className="about-content">
                            <h2>当サロンについて</h2>
                            <div className="p-wrapper">
                                <p>身体の声を聞く。</p>
                                <p>日々忙しく過ごされている中で、たまに訪れる身体からの不調のサインを感じたことはありませんか？</p>
                                <p>
                                    私は仕事に家事に育児に追われ、派手に身体を壊した経験があります。まぁ苦しい…しんどい…誰か助けて。
                                    そんな状態になりました。だからこそ、頑張るあなたに同じ思いはして欲しくない。自分の声を聞いて、和らげて、楽を手に入れましょう！
                                    激務な毎日で苦しさを体験したからこそ、お一人お一人の身体に心に向き合います。
                                </p>
                                <p>筋膜リリースという手技で筋膜にアプローチをしてから筋肉のこわばりをほぐし整えていきます。小難しいことは言いません。ふわっふわな身体と心にするお手伝いをします。</p>
                                <p>そして、身体が楽になった先に何をしたいですか？一緒に目指していきましょう。</p>
                            </div>
                        </div>
                    </article>
                    <article>
                        <div id="about-image2">
                            {/* michan photo */}
                            <img src="/misato.jpg" alt="Salon room" loading="lazy" />
                        </div>
                        <div className="about-content">
                            <h2>セラピスト 江添美里</h2>
                            <div className="p-wrapper">
                                <p> 3児のママでもあるセラピストの江添美里です。以前は長く営業職をしていました。</p>
                                <p>
                                    心子育てをしながらの激務に身体も心もなんならお肌も不調続きの日々でした。それでも好きだった営業のお仕事…全てに全力投球の末、結果かなり疲労が表に出ました。本当に色んな意味で暗黒時代です。何をやっても必死で、結果なんて付いて来ず。
                                </p>
                                <p>
                                    そんな疲れ度MAXな中、ふと我が子が通う保育園で全力で笑う子どもたちと職員さんの姿が目には入りました。本気で楽しんでいる…私もコレがしたい！迷わずセラピストへ転身しました！
                                </p>
                                <p>
                                    皆が喜んで、幸せを感じられる、誰かのお手伝いができる、私と会えてよかったと思ってもらえる、大好きを本気でやれる自分になりたい。そんな一心で３つのスクールに通い、２社でセラピストを経験しました。
                                </p>
                                <p> あなたの毎日を快適にしたい、好きをずっと大好きでいたれるよう、まずは身体を整えましょう。 </p>
                            </div>
                        </div>
                    </article>
                </div>
            </StyledAbout>
        </Layout>
    );
}
