import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Layout from '../components/layout';
import styled from 'styled-components';
import { page } from '../styles/GlobalStyled';
import Card from '../components/Card';
import Button from '../components/Button';
import Link from 'next/link';

const StyledIndex = styled(page)`
    .hero {
        height: 45vh;
        width: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-image: url('/topimage.jpg');
        display: flex;
        justify-content: center;
        align-items: center;
        .hero-content {
            display: flex;
            flex-direction: column;
            max-width: 400px;
            background: rgba(255, 255, 255, 0.4);
            padding: 1.5rem;
            p,
            h1 {
                text-align: center;
            }
            h1 + p {
                font-size: 0.8em;
            }
        }
    }
    .card-wrapper {
        margin: 5rem auto;

        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
        width: 100%;
        height: auto;
    }
`;

export default function index() {
    return (
        <Layout>
            <Head>
                <title>flamingo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet" />
            </Head>

            <StyledIndex>
                {/* this is how an image is done <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}

                <div className="hero">
                    <div className="hero-content">
                        <p>整体　筋膜リリース</p>
                        <h1 className="cursive">flamingo</h1>
                        <p>
                            羽ばたきたくなる身体に… <br />
                            オールハンドで身体を気持ちよく整えます。
                            <br /> 心地よい身体になってあなただけの人生を 思いっきり楽しんでほしい… <br />
                            そんな想いで施術をします。
                        </p>
                    </div>
                </div>

                <div className="card-wrapper">
                    <Card link="/about" linkDesc="about">
                        <p>当サロンについて。</p>
                        <Button>
                            <Link href="/about">
                                <a>About</a>
                            </Link>
                        </Button>
                    </Card>
                    <Card>
                        <p>メニューはこちらからご覧いただけます。</p>

                        <a style={{ display: 'block', padding: 'auto', color: 'white' }} href="/flamingo-menu.pdf" download>
                            <Button>Menu</Button>
                        </a>
                    </Card>
                    <Card>
                        {' '}
                        <p>お問合わせはこちらから。</p>
                        <Button>
                            <Link href="/contact">
                                <a>contact</a>
                            </Link>
                        </Button>
                    </Card>
                </div>
                {/* <Image src="/feather.png" alt="" width={100} height={100} /> */}
            </StyledIndex>
        </Layout>
    );
}
