import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Layout from '../components/layout';
import styled from 'styled-components';

const StyledMenu = styled.div`
    height: 90vh;
    width: 100vw;
    max-width: 1480px;
`;

export default function menu() {
    return (
        <Layout>
            <Head>
                <title>Menu</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet" />
            </Head>
            <StyledMenu>
                <h1>Menu Page</h1>
            </StyledMenu>
        </Layout>
    );
}
